Repository Materials-Consortia/optimade-python-tools, pull requests merged in 2019-11, with the labels that each got.

#74 Added external API validator based on our pydantic models
  openapi.json
  optimade/models/structures.py
  optimade/models/tests/test_bad_structures.json
  optimade/models/tests/test_models.py
  optimade/server/deps.py
  optimade/server/tests/test_server.py
  optimade/validator/__init__.py
  optimade/validator/validator.py
  optimade/validator/validator_model_patches.py
  setup.py
Labels: enhancement

#85 Add sortable field to EntryInfoProperty model
  openapi.json
  optimade/models/entries.py
Labels: schema

#83 Validate illegal fields are not present under attributes and relationships
  optimade/models/jsonapi.py
  optimade/models/structures.py
  optimade/models/tests/test_bad_structures.json
Labels: schema

#91 Add relationships functionality
  optimade/filtertransformers/tests/test_elasticsearch.py
  optimade/models/entries.py
  optimade/models/jsonapi.py
  optimade/models/links.py
  optimade/models/optimade_json.py
  optimade/models/references.py
  optimade/models/tests/test_models.py
  optimade/models/toplevel.py
  optimade/server/main.py
  optimade/server/mappers/structures.py
  optimade/server/tests/test_references.json
  optimade/server/tests/test_server.py
  optimade/server/tests/test_structures.json
  optimade/server/utils.py
  optimade/validator/validator_model_patches.py
Labels: enhancement, help wanted
