Repository Materials-Consortia/optimade-python-tools, pull requests merged in 2020-09, with the labels that each got.

#482 Fix field optonality inconsistency in schema
  openapi/openapi.json
  optimade/models/structures.py
Labels: bug, schema

#490 Update dependencies
  requirements-client.txt
  requirements-docs.txt
  requirements.txt
  setup.py
Labels: dependency_updates

#495 Commit only when necessary
  .github/workflows/update_docs.sh
Labels: CI, bug

#501 Update dependencies
  requirements-client.txt
  requirements-dev.txt
  requirements-docs.txt
  setup.py
Labels: dependency_updates

#505 Make validator respond to KeyboardInterrupts
  optimade/validator/utils.py
Labels: priority/low, validator

#510 Update dependencies
  requirements-client.txt
  requirements-docs.txt
  requirements.txt
  setup.py
Labels: dependency_updates

#511 Move entry schemas to separate submodule
  docs/api_reference/server/schemas.md
  optimade/server/routers/info.py
  optimade/server/routers/utils.py
  optimade/server/schemas.py
  tests/server/test_schemas.py
Labels: enhancement, priority/medium

#503 Add support levels to validator config
  optimade/models/utils.py
  optimade/validator/config.py
  optimade/validator/validator.py
Labels: blocking, validator
