Repository Materials-Consortia/optimade-python-tools, pull requests merged in 2020-06, with the labels that each got.

#336 Specify versions for all setup.py deps
  setup.py
Labels: dependency_updates

#171 Validate lattice_vectors for all null or all float
  optimade/models/structures.py
  tests/models/test_bad_structures.json
  tests/models/test_more_structures.json
Labels: schema

#364 Dependabot updates: numpy, mkdocs-material, mkdocstrings, requests
  .github/dependabot.yml
  requirements-client.txt
  requirements-docs.txt
  requirements.txt
Labels: dependency_updates

#351 Update model descriptions and openapi.json for 1.0.0-rc2
  openapi/index_openapi.json
  openapi/openapi.json
  optimade/models/baseinfo.py
  optimade/models/entries.py
  optimade/models/index_metadb.py
  optimade/models/jsonapi.py
  optimade/models/links.py
  optimade/models/optimade_json.py
  optimade/models/references.py
  optimade/models/structures.py
  optimade/server/query_params.py
  tasks.py
Labels: OpenAPI, priority/high, schema

#367 Bump spec version to 1.0.0-rc.2
  .pre-commit-config.yaml
  INSTALL.md
  openapi/index_openapi.json
  openapi/openapi.json
  optimade-version.json
  optimade/__init__.py
  optimade/models/baseinfo.py
  optimade/models/optimade_json.py
  optimade/models/utils.py
  optimade/server/routers/index_info.py
  optimade/server/routers/info.py
  optimade/server/routers/utils.py
  setup.py
  tasks.py
  tests/models/test_baseinfo.py
  tests/server/test_server_validation.py
Labels: priority/high

#377 Use new action for publishing
  .github/workflows/check_released_tag.py
  .github/workflows/deps_lint.yml
  .github/workflows/publish-on-pypi.yml
  .github/workflows/release_tag_msg.txt
  .github/workflows/update_changelog.sh
  setup.py
Labels: CI, dependency_updates, enhancement, tests

#378 Fix publish workflow - final(TM) fix
  .github/workflows/publish-on-pypi.yml
  .gitignore
Labels: bug
