Repository Materials-Consortia/optimade-python-tools, pull requests merged in 2020-07, with the labels that each got.

#385 Set implementation version in config by default
  optimade/server/config.py
Labels: enhancement, priority/medium

#388 Update dependencies
  requirements-client.txt
  requirements-docs.txt
  requirements.txt
  setup.py
Labels: dependency_updates

#412 Update dependencies
  requirements-client.txt
  requirements-dev.txt
  requirements-docs.txt
  requirements.txt
  setup.py
  tests/adapters/structures/utils.py
Labels: dependency_updates

#395 Fix some validator-specific crashes
  optimade/models/entries.py
  optimade/validator/__init__.py
  optimade/validator/data/filters.txt
  optimade/validator/validator.py
  optimade/validator/validator_model_patches.py
  setup.py
Labels: priority/high, validator

#414 Fix /vMAJOR/info in index server
  optimade/server/main_index.py
  tests/server/test_server_validation.py
  tests/server/utils.py
Labels: bug
