Repository Materials-Consortia/optimade-python-tools, pull requests merged in 2021-02, with the labels that each got.

#697 Update dependencies
  .github/workflows/publish-on-pypi.yml
  requirements-client.txt
  requirements-dev.txt
  requirements-docs.txt
  requirements.txt
  setup.py
Labels: CI, dependency_updates

#707 Update dependencies
  requirements-client.txt
  requirements-dev.txt
  requirements-docs.txt
  requirements.txt
  setup.py
Labels: dependency_updates

#631 Update species->mass field following specification change
  openapi/openapi.json
  optimade/adapters/structures/aiida.py
  optimade/adapters/structures/ase.py
  optimade/adapters/structures/cif.py
  optimade/adapters/structures/jarvis.py
  optimade/adapters/structures/proteindatabank.py
  optimade/adapters/structures/pymatgen.py
  optimade/adapters/structures/utils.py
  optimade/adapters/warnings.py
  optimade/models/structures.py
  pytest.ini
  tests/adapters/structures/special_species.json
  tests/adapters/structures/test_aiida.py
  tests/adapters/structures/test_structures.py
  tests/models/test_data/test_bad_structures.json
  tests/models/test_data/test_good_structures.json
Labels: OPTIMADE v1.0, models, priority/high, schema
