Repository Materials-Consortia/optimade-python-tools, pull requests merged in 2021-11, with the labels that each got.

#991 Update dependencies
  .pre-commit-config.yaml
  requirements-docs.txt
Labels: dependency_updates, CI

#993 Update dependencies
  requirements-client.txt
Labels: dependency_updates, CI

#998 Update dependencies
  .pre-commit-config.yaml
  requirements.txt
  setup.py
Labels: dependency_updates, CI, blocked

#879 Tidy up old grammars, add a development grammar for v1.2 and update filterparser tests
  optimade/filterparser/lark_parser.py
  optimade/grammar/v0.9.5.lark
  optimade/grammar/v0.9.6.lark
  optimade/grammar/v0.9.7.lark
  optimade/grammar/v1.0.1.lark
  optimade/grammar/v1.1.0.lark
  optimade/grammar/v1.2.0.develop.lark
  tests/filterparser/test_filterparser.py
  tests/filterparser/testfiles/parse_001.inp
  tests/filterparser/testfiles/parse_002.inp
  tests/filterparser/testfiles/parse_003.inp
  tests/filterparser/testfiles/parse_004.inp
  tests/filterparser/testfiles/parse_005.inp
  tests/filterparser/testfiles/parse_006.inp
  tests/filterparser/testfiles/parse_007.inp
  tests/filterparser/testfiles/parse_008.inp
  tests/filterparser/testfiles/parse_009.inp
  tests/filterparser/testfiles/parse_010.inp
  tests/filterparser/testfiles/parse_011.inp
  tests/filterparser/testfiles/parse_012.inp
  tests/filterparser/testfiles/parse_013.inp
  tests/filterparser/testfiles/parse_014.inp
  tests/filtertransformers/test_elasticsearch.py
Labels: grammar, priority/low, tests

#1004 Update dependencies
  .pre-commit-config.yaml
Labels: dependency_updates, CI
