Repository Materials-Consortia/optimade-python-tools, pull requests merged in 2021-03, with the labels that each got.

#725 Update dependencies
  requirements-client.txt
  requirements-dev.txt
  requirements-docs.txt
  requirements.txt
  setup.py
  tests/adapters/structures/utils.py
Labels: dependency_updates

#734 Update dependencies
  optimade/adapters/structures/pymatgen.py
  requirements-client.txt
  requirements-docs.txt
  setup.py
  tests/adapters/structures/test_pymatgen.py
Labels: dependency_updates

#736 Disable all floating-point comparisons during validation
  optimade/validator/config.py
  optimade/validator/validator.py
  tests/server/test_server_validation.py
Labels: priority/medium, validator

#760 Update dependencies
  .github/workflows/deps_lint.yml
  .github/workflows/publish-on-pypi.yml
  .pre-commit-config.yaml
  requirements-client.txt
  requirements-dev.txt
  requirements-docs.txt
  requirements.txt
  setup.py
Labels: CI, dependency_updates
