Repository Materials-Consortia/optimade-python-tools, pull requests merged in 2021-05, with the labels that each got.

#787 Update dependencies
  .github/workflows/publish-on-pypi.yml
  .pre-commit-config.yaml
  openapi/index_openapi.json
  openapi/openapi.json
  optimade/filtertransformers/base_transformer.py
  optimade/filtertransformers/elasticsearch.py
  optimade/filtertransformers/mongo.py
  optimade/models/baseinfo.py
  optimade/models/entries.py
  optimade/models/optimade_json.py
  optimade/models/utils.py
  optimade/server/entry_collections/mongo.py
  optimade/server/main.py
  optimade/server/main_index.py
  optimade/server/routers/landing.py
  optimade/validator/utils.py
  optimade/validator/validator.py
  requirements-client.txt
  requirements-dev.txt
  requirements-docs.txt
  requirements.txt
  setup.py
  tests/filtertransformers/test_mongo.py
  tests/server/query_params/test_filter.py
  tests/server/query_params/test_sort.py
  tests/server/test_server_validation.py
  tests/server/utils.py
Labels: CI, dependency_updates

#794 Filter out extension endpoints before validation
  optimade/validator/config.py
  optimade/validator/validator.py
Labels: priority/medium, validator

#803 Update GH actions
  .github/workflows/deps_lint.yml
  .github/workflows/publish-on-pypi.yml
Labels: CI

#811 Update INSTALL docs
  CONTRIBUTING.md
  INSTALL.md
Labels: docs, priority/medium
