Repository Materials-Consortia/optimade-python-tools, pull requests merged in 2022-02, with the labels that each got.

#1063 Update dependencies
  .pre-commit-config.yaml
  optimade/models/structures.py
  requirements-dev.txt
  requirements-docs.txt
  requirements.txt
  setup.py
  tests/adapters/structures/utils.py
  tests/models/test_structures.py
Labels: dependency_updates, CI

#1066 Bump elasticsearch version to avoid CVE-2021-44832
  .github/workflows/ci.yml
  INSTALL.md
Labels: security

#1070 Update dependencies
  requirements-dev.txt
  requirements.txt
  setup.py
Labels: dependency_updates, CI

#1082 Do not use Jinja to generate the landing page
  optimade/server/routers/landing.py
  optimade/server/routers/static/landing_page.html
  requirements.txt
Labels: blocking

#1085 Use type `ID!` instead of `String!`
  .github/workflows/ci_automerge_dependabot.yml
Labels: blocking

#1087 Remove Jinja dep from setup.py
  setup.py
Labels: bug, dependency_updates, CI, skip_changelog

#1081 Jinja2 version workaround
  requirements-docs.txt
Labels: CI, skip_changelog

#1089 Add markupsafe to setup.py
  setup.py
Labels: dependency_updates, CI, skip_changelog
