Repository Materials-Consortia/optimade-python-tools, pull requests merged in 2022-10, with the labels that each got.

#1343 Update dependencies
  requirements-client.txt
  requirements-dev.txt
  requirements-docs.txt
  requirements.txt
Labels: dependency_updates, CI

#1345 Refreshing the README
  README.md
Labels: docs, skip_changelog

#1354 Docs fixes: revert mkdocstrings handler and fix JOSS badge
  README.md
  requirements-docs.txt
  setup.py
Labels: docs, skip_changelog

#1371 Support new remote swagger.io validator format
  tasks.py
Labels: OpenAPI, CI

#1369 Do not enforce minimum value of `page_number` at model level
  openapi/index_openapi.json
  openapi/openapi.json
  optimade/server/entry_collections/entry_collections.py
  optimade/server/query_params.py
  tests/server/middleware/test_query_param.py
Labels: OpenAPI
