Repository Materials-Consortia/optimade-python-tools, pull requests merged in 2022-11, with the labels that each got.

#1376 Update dependencies
  .github/workflows/ci_dependabot.yml
  .pre-commit-config.yaml
  requirements-client.txt
  requirements-dev.txt
  requirements-docs.txt
  requirements-http-client.txt
  requirements.txt
  setup.py
Labels: dependency_updates, CI

#1385 Update dependencies
  .github/workflows/ci.yml
  requirements-client.txt
  requirements-dev.txt
  requirements-docs.txt
  requirements.txt
  setup.py
Labels: dependency_updates, CI

#1362 Support Python 3.11
  .github/workflows/ci.yml
  setup.py
Labels: enhancement

#1398 Tweak Procfile for fly deployment
  Procfile
Labels: skip_changelog

#1399 Re-revert Procfile for Fly
  Procfile
Labels: deployment, skip_changelog

#1401 Add fly config file to CI
  .github/fly.toml
  .github/workflows/ci_cd_updated_master.yml
Labels: deployment, skip_changelog

#1400 Complete migration from Heroku to Fly
  .github/workflows/ci.yml
  .github/workflows/ci_cd_updated_master.yml
  README.md
  docs/concepts/validation.md
  docs/getting_started/client.md
  tests/server/test_client.py
Labels: deployment

#1406 Update dependencies
  .pre-commit-config.yaml
  requirements-client.txt
  requirements-dev.txt
  requirements-docs.txt
  requirements-http-client.txt
  requirements-server.txt
  requirements.txt
  setup.py
Labels: dependency_updates, CI
