Repository Materials-Consortia/optimade-python-tools, pull requests merged in 2022-01, with the labels that each got.

#1036 Make NumPy requirement py version-specific
  docs/getting_started/filtering.md
  optimade/filterparser/lark_parser.py
  requirements-client.txt
Labels: blocking

#1031 Update dependencies
  .github/workflows/cd_release.yml
  .github/workflows/ci.yml
  .github/workflows/ci_dependabot.yml
  .pre-commit-config.yaml
  requirements-client.txt
  requirements-docs.txt
  requirements.txt
  setup.py
  tests/adapters/structures/test_pymatgen.py
Labels: dependency_updates, CI

#1044 Update dependencies
  .github/workflows/ci_dependabot.yml
  requirements-docs.txt
  requirements.txt
  setup.py
Labels: dependency_updates, CI

#1049 Update dependencies
  requirements-client.txt
  requirements-docs.txt
  requirements.txt
  setup.py
Labels: dependency_updates, CI

#1051 Lower validator default read timeout and allow it to be customised
  optimade/validator/utils.py
  optimade/validator/validator.py
Labels: enhancement, validator

#1053 Attempt to fix syntax for actions workflow
  .github/workflows/cd_release.yml
Labels: dependency_updates

#1054 Properly exclude dependency updates from changelog, and add unreleased changelog
  .github/workflows/cd_release.yml
  .github/workflows/ci_cd_updated_master.yml
Labels: dependency_updates

#1055 Set future-release label for changelog
  .github/workflows/ci_cd_updated_master.yml
Labels: dependency_updates, CI

#1062 Use `build` package to build distributions
  .github/workflows/cd_release.yml
  MANIFEST.in
  requirements-dev.txt
  setup.py
  tests/test_setup.py
Labels: blocking
