Repository Materials-Consortia/optimade-python-tools, pull requests merged in 2022-07, with the labels that each got.

#1255 Update dependencies
  .pre-commit-config.yaml
  requirements-client.txt
  requirements-docs.txt
  requirements.txt
  setup.py
Labels: dependency_updates, CI

#1211 Add meta->schema validation warning
  optimade/validator/validator.py
Labels: validator

#1179 Drop support for Python 3.7
  .github/workflows/ci.yml
  optimade/__init__.py
  requirements-client.txt
  requirements-docs.txt
  requirements.txt
  setup.py
Labels: python, for_next_release

#1275 Update dependencies
  requirements-client.txt
  requirements-dev.txt
  requirements-docs.txt
  requirements-http-client.txt
  requirements.txt
  setup.py
Labels: dependency_updates, CI

#1280 Remove final reference to `typing_extensions` and readthedocs config
  .readthedocs.yml
  optimade/server/config.py
Labels: dependency_updates, skip_changelog
