Repository Materials-Consortia/optimade-python-tools, pull requests merged in 2023-11, with the labels that each got.

#1846 Update dependencies
  .pre-commit-config.yaml
  requirements-dev.txt
  requirements-docs.txt
Labels: dependency_updates, CI

#1857 Update dependencies
  .pre-commit-config.yaml
  optimade/server/main.py
  optimade/server/main_index.py
  pyproject.toml
  requirements-dev.txt
  requirements-docs.txt
  requirements-http-client.txt
  requirements-server.txt
  requirements.txt
Labels: dependency_updates, CI

#1861 Disable inserting test data in fly demo server
  tests/test_config.json
Labels: skip_changelog

#1862 Revert test data insertion and instead increase fly swap
  .github/fly.toml
Labels: skip_changelog

#1864 Debugging fly configuration
  .github/fly.toml
  tests/test_config.json
Labels: skip_changelog

#1865 Manually generate Fly environment in CI
  .github/workflows/ci_cd_updated_master.yml
Labels: skip_changelog

#1866 Try to resolve new fly builder deps
  .github/workflows/ci_cd_updated_master.yml
Labels: skip_changelog

#1867 Update config file location for Fly deployment
  .github/fly.toml
  .github/workflows/ci_cd_updated_master.yml
Labels: skip_changelog

#1870 Try to force fly to use the config file
  .github/fly.toml
  .github/workflows/ci_cd_updated_master.yml
  Procfile
Labels: deployment, skip_changelog

#1871 Try to force fly to use the config file in Procfile
  Procfile
Labels: deployment, skip_changelog
