Repository Materials-Consortia/optimade-python-tools, pull requests merged in 2024-01, with the labels that each got.

#1921 Update dependencies
  .pre-commit-config.yaml
  requirements-client.txt
  requirements-dev.txt
  requirements-docs.txt
  requirements-http-client.txt
  requirements-server.txt
  requirements.txt
Labels: dependency_updates, CI

#1925 Client: add ability to count the number of results using binary search over pagination
  optimade/client/cli.py
  optimade/client/client.py
  tests/server/test_client.py
  tests/test_config.json
Labels: enhancement, client

#1932 More attempts to fix-up CI for backport releases
  .github/workflows/cd_release.yml
Labels: skip_changelog

#1953 Update dependencies
  .pre-commit-config.yaml
  pyproject.toml
  requirements-client.txt
  requirements-dev.txt
  requirements-docs.txt
  requirements-server.txt
  requirements.txt
Labels: dependency_updates, CI

#1955 Add `requests` timeout when getting providers list
  optimade/utils.py
Labels: bug
